# Generated by Django 5.0.2 on 2024-02-22 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.TextField(verbose_name="About")),
                (
                    "joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="Joined"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="newuser",
            name="account",
            field=models.ManyToManyField(to="user.account", verbose_name="User"),
        ),
        migrations.AddField(
            model_name="newuser",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.profile",
                verbose_name="Profile",
            ),
        ),
    ]
