# Generated by Django 5.0.2 on 2024-02-22 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_account_profile_newuser_account_newuser_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newuser",
            name="profile",
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="newuser",
            name="account",
            field=models.ManyToManyField(
                blank=True, to="user.account", verbose_name="Account"
            ),
        ),
    ]
