# Generated by Django 5.0.2 on 2024-02-22 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_newuser_profile_profile_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name_plural": "Accounts"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name_plural": "profiles"},
        ),
    ]
