# Generated by Django 5.0.2 on 2024-02-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_account_options_alter_profile_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "Account", "verbose_name_plural": "Accounts"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
    ]
