# Generated by Django 5.0.2 on 2024-02-22 20:33

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tree", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        max_digits=10,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        max_digits=10,
                        verbose_name="Longitude",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="plantedtree",
            options={"verbose_name_plural": "Planted Trees"},
        ),
        migrations.AlterModelOptions(
            name="tree",
            options={"verbose_name_plural": "Trees"},
        ),
        migrations.AddField(
            model_name="plantedtree",
            name="location",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="tree.location",
                verbose_name="Location",
            ),
            preserve_default=False,
        ),
    ]
