# Generated by Django 5.0.2 on 2024-02-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0002_location_alter_plantedtree_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "Location", "verbose_name_plural": "Locations"},
        ),
        migrations.AlterModelOptions(
            name="plantedtree",
            options={
                "verbose_name": "Planted tree",
                "verbose_name_plural": "Planted trees",
            },
        ),
        migrations.AlterModelOptions(
            name="tree",
            options={"verbose_name": "Tree", "verbose_name_plural": "Trees"},
        ),
    ]
